-- Pilotos
INSERT INTO drivers (first_name, last_name, team_id, created_at, updated_at) VALUES
('Norbert', 'Michelisz', 1, NOW(), NOW()),
('Yann', 'Ehrlacher', 2, NOW(), NOW()),
('Mikel', 'Azcona', 1, NOW(), NOW()),
('Esteban', 'Guerrieri', 4, NOW(), NOW()),
('Néstor', 'Girolami', 1, NOW(), NOW()),
('Thed', 'Björk', 2, NOW(), NOW()),
('Ma Qing', 'Hua', 2, NOW(), NOW()),
('Santiago', 'Urrutia', 2, NOW(), NOW()),
('John', 'Filippi', 3, NOW(), NOW()),
('Marco', 'Butti', 4, NOW(), NOW()),
('Sami', 'Taoufik', 3, NOW(), NOW()),
('Sandro', 'Pelatti', 5, NOW(), NOW()),
('Víctor', 'Fernández', 6, NOW(), NOW()),
('Demir', 'Eröge', 6, NOW(), NOW()),
('Filippo', 'Barberi', 6, NOW(), NOW()),
('Philipp', 'Mattersdorfer', 6, NOW(), NOW()),
('Ramazan', 'Kaya', 6, NOW(), NOW()),
('Jacopo', 'Giuseppe Cimenes', 6, NOW(), NOW()),
('Tony', 'Verhulst', 6, NOW(), NOW()),
('Giulio', 'Valentini', 6, NOW(), NOW());